# Docker compose used for development environment only.

version: '3.2'

services:

  db:
    image: jimmydockerhub/boxer-ratings-mysql:latest
    container_name: mysql
    restart: always
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_USER: root
      MYSQL_DATABASE: boxers